#!/bin/bash


rm -rf build
mkdir build
cd build

. /etc/lsb-release	

SRCDIR=openvpn-2.2.1
#apt-get source openvpn=2.2.1

# This gets the source 
wget http://archive.ubuntu.com/ubuntu/pool/main/o/openvpn/openvpn_2.2.1-8ubuntu1.dsc
wget http://archive.ubuntu.com/ubuntu/pool/main/o/openvpn/openvpn_2.2.1.orig.tar.gz
wget http://archive.ubuntu.com/ubuntu/pool/main/o/openvpn/openvpn_2.2.1-8ubuntu1.debian.tar.gz

#get required code out of the box
tar xf openvpn_2.2.1.orig.tar.gz
tar xf openvpn_2.2.1-8ubuntu1.debian.tar.gz | patch -p1
# press No on all the patch questions

# copy patches from debian/patches/ to the openvpn/debian/patches/ folder
cp -r ../changes/* $SRCDIR/
cp -r debian/patches/* $SRCDIR/debian/patches/
#(cd $SRCDIR; zcat ../openvpn_2.2.1-8ubuntu1.debian.tar.gz | patch -p1)
#cp -r ../debian/patches/* ./debian/patches/
# copy the changes/debian to openvpn
#cp -r ../changes/* .

# build
cd $SRCDIR
automake --add-missing
chmod a+x debian/rules
dpkg-buildpackage -rfakeroot -uc -b


#cp -r ../changes/* $SRCDIR
#cd $SRCDIR
#chmod a+x debian/rules
#dpkg-buildpackage -rfakeroot -uc -b
#cd ../..

mv build/*.deb ..
mv build/*.changes ..
rm -rf build

